global:
    scrape_interval: 15s
    external_labels:
        monitor: 'cadvisor-monitor'

scrape_configs:
    - job_name: 'cadvisor-exporter'
      static_configs:
          - targets: ['211.183.3.201:8080', '211.183.3.202:8080']

    - job_name: 'node-exporter'
      static_configs:
          - targets: ['211.183.3.201:9100', '211.183.3.202:9100']

