global:
    scrape_interval: 15s
    external_labels:
        monitor: 'node-monitor'
scrape_configs:
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['211.183.3.201:9100', '211.183.3.202:9100']
