version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.manager1 == true
    volumes:
      - ./prometeus/prom_node.yml:/etc/prometheus/prometheus.yml
      - ./prometeus/prom_cad.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:4.4.3
    ports:
      - "3000:3000"
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.manager1 == true
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  cadvisor:
    image: google/cadvisor:v0.24.1
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    external: true
